---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "07:00"
      timezone: "Europe/Amsterdam"
      
  - package-ecosystem: pip
    directory: /mag-cli
    schedule:
      interval: daily
      time: "07:00"
      timezone: "Europe/Amsterdam"

  - package-ecosystem: docker
    directory: /mag-sh
    schedule:
      interval: weekly
      day: thursday
      time: "07:00"
      timezone: "Europe/Amsterdam"
