apiVersion: v2
appVersion: 1.5.9
#dependencies:
#- condition: dagster-user-deployments.enableSubchart
#  name: dagster-user-deployments
#  repository: ""
#  version: 1.5.9
#- condition: postgresql.enabled
#  name: postgresql
#  repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami/index.yaml
#  version: 8.1.0
#- condition: rabbitmq.enabled
#  name: rabbitmq
#  repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami/index.yaml
#  version: 6.16.3
#- condition: redis.internal
#  name: redis
#  repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami/index.yaml
#  version: 12.7.4
description: The data orchestration platform built for productivity.
icon: https://dagster.io/images/brand/logos/dagster-primary-mark.png
keywords:
- analytics
- data-orchestrator
- data-pipelines
- etl
- workflow
kubeVersion: '>= 1.18.0-0'
maintainers:
- email: support@dagsterlabs.com
  name: Dagster Labs
  url: https://dagster.io/about
name: dagster
sources:
- https://github.com/dagster-io/dagster/tree/master/helm/dagster
type: application
version: 1.5.9
