apiVersion: v2
appVersion: 1.21.1-3.9.1
description: Helm charts for deploying Apache Drill on a Kubernetes cluster
home: http://drill.apache.org/
keywords:
- apache
- drill
- zookeeper
- magasin
- unicef
maintainers:
- email: merlos@users.noreply.github.com
  name: merlos
name: drill
sources:
- https://github.com/unicef/magasin-drill
type: application
version: 0.6.1
